### PR TITLE
Fixes to support HDFS support for all three modes

### PR DESCRIPTION
**Pull request by bdrosen96**

### CODE REVIEW

**Comment by jettify** [comment]
lets merge this

**Comment by ghost** [comment]
I'm trying to get hadoop.rpc.protection value of privacy to work in libhdfs3. Does this require  bdrosen96/libgsasl as replacement to libgsasl? Thanks for any help.

**Comment by bdrosen96** [comment]
I believe so

**Comment by bdrosen96** [comment]
You also need the forked version of libhdfs: https://github.com/bdrosen96/libhdfs3

**Comment by ghost** [comment]
Thanks for the quick reply. I used your kerberos impersonation code; it worked great. I have a client that has set authentication to privacy, so I need your fixes. Hopefully I can get it working.

**Comment by ghost** [comment]
Brett:

 

I’m getting an error at a customer site:

 

error in hdfsBuilderConnect () hdfs::hdfsrpcexception: hdfsfailoverexception: failed to invoke rpc call "getfsstats" on server "edpprod:8020" caused by: hdfsnetworkconnectexception: failed to resolve address "edpprod:8020" name or service not known 

 

Would you have any idea as to the cause of this or where I should look?

 

If you have the time to respond, I appreciate, but understand if you don’t.

 

Best regards,

 

John Parke

**Comment by bdrosen96** [comment]
Seems like either a network or config issue:

failed to resolve address "edpprod:8020" name or service not known

This indicates to me that it  could not resolve IP for host edpprod. Perhaps host name is wrong, or you need domain name or resolv.conf is not correct.

https://github.com/Pivotal-Data-Attic/pivotalrd-libhdfs3/blob/59789c90f2f42726900eb2e417eea88a670f0b3c/src/network/TcpSocket.cpp#L167-L178

**Comment by ghost** [comment]
Brett:

 

I appreciate information. You have done a great job implementing the Kerberos code.

 

Thanks again,

 

John

**Comment by ghost** [comment]
Brett:

 

Sorry to bug you again, but have you ever seen this error before:

 

RpcChannel.cpp: 819: HdfsRpcException: RPC channel to "uxpapessmndp03.dstcorp.net:8020" got protocol mismatch: RPC channel cannot find pending call: id = -33.

 

Thanks,

 

John

**Comment by bdrosen96** [comment]
I think so, but am not 100% sure. More than likely this is a result of the HDFS server config not matching the client config for libhdfs, particularly with regards to encryption settings or the like. Checking the hdfs name node or data node log files might provide more details for you.

**Comment by ghost** [comment]
Brett:

 

Thanks. Could hdfs-client.xml be a source of problems?

**Comment by bdrosen96** [comment]
Not sure if that would be read by the lib or not. I've never used this in a case where the xml file exists on the host and have just passed params in manually.

**Comment by ghost** [comment]
Yes, I realized it was a dumb question after I asked it.

 

I looking through 1 million line logs and packet traces. I can see the initial rpc request going out, I believe. 

 

It is failing on the getfstats:

2017-09-01 13:08:25.270055, p41201, th139628624087360, ERROR Failed to invoke RPC call "getFsStats" on server "uxpapessmndp03.dstcorp.net:8020":

RpcChannel.cpp: 819: HdfsRpcException: RPC channel to "uxpapessmndp03.dstcorp.net:8020" got protocol mismatch: RPC channel cannot find pending call: id = -33.

 

This is happening at a client site; its HA. I have set up an environment as close as possible to theirs. My tests all run perfectly.

 

Don’t know what the heck to try next.

 

Appreciate your help.

 

John

**Comment by ghost** [comment]
Brett:

 

Do you know what happens if the same rpc request is sent; i.e. a retransmission?

 

Thanks,

 

John

**Comment by bdrosen96** [comment]
This almost certainly is a mismatch between client and server. I would suggest checking such things as:

hdfs getconf -confKey hadoop.security.authentication 
hdfs getconf -confKey hadoop.rpc.protection

hdfs getconf -confKey "dfs.encrypt.data.transfer"
hdfs getconf -confKey "dfs.block.access.token.enable"
hdfs getconf -confKey "dfs.encrypt.data.transfer.algorithm"
hdfs getconf -confKey "dfs.encrypt.data.transfer.cipher.suites"

Most of the later settings would be for data transfer rather than Name Node RPC, so they likely would not be an issue. Also, the getconf results can sometimes lie.

You should also check to be sure you are using the modified libgsasl with the modified libhdfs otherwise this won't work at all.

You also need to be sure that you are passing in parameters to libhdfs or hdfs3 if using python.

**Comment by ghost** [comment]
Brett:

 

Thanks for the detailed reply. I really appreciate it.

 

I will check all of the things you said.

 

Very best regards,

 

John

**Comment by ghost** [comment]
Brett:

 

I thought I would give you an update on what I found as it might be of interest to you.

 

I noticed in the packet trace captured at the client’s site that the RPC calls (port 8020) are not encrypted, i.e. they are in plain text.

 

The trace also shows the server sending a QOP of “auth-conf” indicator to the client. 

 

This indicates that the server is requesting a hadoop.rpc.protection value of “privacy”.

 

So, I think what is happening is that the server is sending encrypted messages back to the client, 

 

but the client is communicating in non-encrypted mode; so the client can’t understand the message. 

 

I have run the same exact test program at my own site with different results. 

 

At my site, RPC communications are encrypted with the “privacy” setting and everything works fine.

 

This would seem to indicate that the customer’s configuration is not correct, which is what you thought.

 

Best regards,

 

John

**Comment by ghost** [comment]
Brett:

 

I am trying to re-build your libgsasl. If I run automake in the main directory, I get:

 

error: required file 'config.h.in' not found

 

Should I run from another directory?

 

Thanks,

 

John

**Comment by bdrosen96** [comment]
Something like this:

 curl -L -o /tmp/libgsasl-1.8.0.tar.gz  https://github.com/bdrosen96/libgsasl/archive/1.8.1_complete.tar.gz \
    && mkdir /tmp/libgsasl \
    && tar -xvzf /tmp/libgsasl-1.8.0.tar.gz -C /tmp/libgsasl \
    && cd /tmp/libgsasl/libgsasl-1.8.1_complete/lib \
    && ./configure --with-gssapi-impl=mit \
    && make install \
    && rm -rf /tmp/libgsasl \
    && rm /tmp/libgsasl-1.8.0.tar.gz

**Comment by ghost** [comment]
Thanks.

**Comment by bdrosen96** [comment]
Just pushed some PRs to my version of libhdfs3 that I think may fix the issues you were seeing with mismatch. They should fix a specific bug, also introduce two new parameters that will let you manually specify the protection settings for data transfer as well as rpc.

**Comment by ghost** [comment]
Brett:

 

Thanks. I found that the problem was in: 

 

std::string SaslClient::evaluateChallenge (const std::string &challenge)

 

=>>int qop = (int) decoded.c_str () [0];

 

The qop was being set incorrectly here. The value I see in my lab setting is 0x04, at the client site 0x60. This value caused the client to set qop to authenticate.

 

Making a change to this got me through authentication. Now I am failing in the write to the datanode.

 

The client site has:

 

  <property>

    <name>dfs.data.transfer.protection</name>

    <value>privacy</value>

  </property>

 

This apparently uses sasl for the datanode messages. I suspect the problem is in:

 

void DataTransferProtocolSender::writeBlock

 

Which is called from: void PipelineImpl::createBlockOutputStream

 

I think that the message is being rejected by the server. The server closes the connection while the client is waiting on an ack from the server.

 

Does this sound plausible to you?

 

I really appreciate all of the help you’ve given. Wandering through a library I just recently started using is a real headache.

 

John

**Comment by bdrosen96** [comment]
The evaluateChallenge issue should be fixed by the combination of:

https://github.com/bdrosen96/libhdfs3/pull/18
https://github.com/bdrosen96/libhdfs3/pull/19
https://github.com/bdrosen96/libhdfs3/pull/20
https://github.com/bdrosen96/libhdfs3/pull/21

Those may also fix the other issue as well. Data Transfer encryption should support both SASL style and AES style.

**Comment by ghost** [comment]
Thanks!

**Comment by bdrosen96** [comment]
To make sure data transfer protection is enabled, make sure you are passing in:

dfs.encrypt.data.transfer as true.

You may or may not also need to specify dfs.block.access.token.enable

**Comment by ghost** [comment]
Ok. Thanks.

**Comment by ghost** [comment]
Brett:

 

I am getting this error now:

 

Caused by

DataTransferProtocolSender.cpp: 468: HdfsRpcException: DataNode to "uxpapessdndp07.dstcorp.net(10.225.48.19)" got protocol mismatch: got error reading SASL response: DIGEST-MD5: IO error acquiring password.

 

Any ideas?

 

Thanks,

 

John

**Comment by bdrosen96** [comment]
You should  check setting for dfs.block.access.token.enable to make sure you are using correct token for data transfer. There are at least two possible tokens it might use for this.

This error comes from server and could also indicate a number of different errors. Checking data node logs would likely also be helpful.

**Comment by ghost** [comment]
Thanks.

**Comment by ghost** [comment]
Brett:

 

I set the following:

 

      config.setSecureDatanode (true);

      config.setEncryptedDatanode(true);

      config.setDataProtection(Protection::CONF);

 

And it worked fine.

 

Thanks,

 

John

**Comment by bdrosen96** [comment]
Good to hear that. If you are using python you should be able to do the same thing with pars:

dfs.block.access.token.enable=true
dfs.encrypt.data.transfer=true
dfs.data.transfer.protection=privacy

I think, to avoid needing to modify the code (using the latest version of the codebase)

**Comment by ghost** [comment]
Brett:

 

Only using C++ for now. Only issue I am having is with the determination of the active namenode in HA.

 

I hardcoded the active namenode for my test program. There should be a programmatic way of doing this. I guess with RPC call.

**Comment by bdrosen96** [comment]
If this is an HA system, it should be able to test the name node and fallback to active if first one is not active.

**Comment by ghost** [comment]
Are you saying the functionality is already there?

**Comment by bdrosen96** [comment]
Pretty sure. Look at:

https://github.com/bdrosen96/libhdfs3/blob/apache-rpc-9/src/server/NamenodeProxy.cpp#L217-L240

**Comment by ghost** [comment]
Cool. Thanks!

**Comment by ghost** [comment]
Brett:

 

I am getting the following error:

 

mechanism: "DIGEST-MD5"

protocol: ""

serverId: "default"

challenge: "realm=\"default\",nonce=\"36jDdAeMhNXKiNHNfwZZ5xaHVrJ4zEt/htjkCxNf\",qop=\"auth-conf\",charset=utf-8,cipher=\"3des,rc4,des,rc4-56,rc4-40\",algorithm=md5-sess"

 

2017-Sep-22 10:57:35.826434 RpcSaslProto_SaslState_NEGOTIATE

2017-Sep-22 10:57:35.826443 SaslClient::evaluateChallenge

2017-Sep-22 10:57:35.826482 gsasl_step rc=55 challenge.size=149 outputSize=0 gsasl_step error=Authentication failed because the password was not provided.

2017-Sep-22 10:57:35.833244 error message=AccessControlException: Failed to evaluate challenge: Authentication failed because the password was not provided. errno=13

 

Can you point me in right direction?

 

John

**Comment by bdrosen96** [comment]
Is this for RPC connection or data connection? Is this using kerberos ticket or token?

**Comment by ghost** [comment]
This is for RPC and Kerberos. It’s happening at connect. I expected to see mechanism GSSAPI, but I’m seeing DIGEST-MD5.

**Comment by bdrosen96** [comment]
When we call this via python we do:

hdfsBuilderSetKerbTicketCachePath to point to ticket cache file location. That invokes src/client/Hdfs.cpp to set hadoop.security.kerberos.ticket.cache.path in the session config object which weill cause getKerberosCachePath on that object to return the path. hadoop.security.authentication in session config also needs to be set to kerberos I believe.

Additionally, when filesystem connect is called, token cannot be passed in

**Comment by ghost** [comment]
OK. Thanks. Been working on this since late last night. Appreciate any and all help.

**Comment by ghost** [comment]
Brett:

 

One last question.

 

https://github.com/bdrosen96/libhdfs3 

 

The clone or download selection will select current version with all your changes?

 

Thanks,

 

John

**Comment by bdrosen96** [comment]
I believe so, but you want to be sure to use correct branch, apache-rpc-9 if you clone.

**Comment by ghost** [comment]
Brett:

 

Your information was the clue I needed. It was a config issue.

 

Thanks,

 

John

**Pull request merged**
